<?php

return [
    App\Providers\AppServiceProvider::class,
    App\Providers\HorizonServiceProvider::class,
    Modules\AI\Providers\AIServiceProvider::class,
    Modules\Alerts\Providers\AlertsServiceProvider::class,
    Modules\Assets\Providers\AssetsServiceProvider::class,
    Modules\Audit\Providers\AuditServiceProvider::class,
    Modules\Banking\Providers\BankingServiceProvider::class,
    Modules\Billing\Providers\BillingServiceProvider::class,
    Modules\Budget\Providers\BudgetServiceProvider::class,
    Modules\Buildings\Providers\BuildingsServiceProvider::class,
    Modules\Business\Providers\BusinessServiceProvider::class,
    Modules\Core\Providers\CoreServiceProvider::class,
    Modules\Documents\Providers\DocumentsServiceProvider::class,
    Modules\Family\Providers\FamilyServiceProvider::class,
    Modules\I18n\Providers\I18nServiceProvider::class,
    Modules\Investment\Providers\InvestmentServiceProvider::class,
    Modules\Ledger\Providers\LedgerServiceProvider::class,
    Modules\Recurring\Providers\RecurringServiceProvider::class,
    Modules\Reports\Providers\ReportsServiceProvider::class,
    Modules\Search\Providers\SearchServiceProvider::class,
    Modules\Sync\Providers\SyncServiceProvider::class,
    Modules\Travel\Providers\TravelServiceProvider::class,
];
